### ISSUE TITLE
Piranha.Manager: App PageTypes/BlockTypes caching causing issues

### ISSUE THREAD

**Issue by willwolfram18** [TheWolfA2/piranha.core#4]
### Problem
`Piranha.App` performs caching with the `BlockTypes` and `PageTypes` properties. While this makes sense in a production environment, this posses an issue with unit tests since the values in `App` persist between unit tests.

### Possible Solutions
* Expose an `internal App.ForceInit()` to unit tests, which would set `instance.isInitialized = false;` and then run the `App.Init()` method again
* Discuss a different caching scheme that prevents such an issue from occurring
    * This is one of the goals of [#9](https://github.com/PiranhaCMS/prianha.core/issues/9)

**Comment by tidyui** [comment]
Updated controllers to use the Api instead of the cached properties of the `App` singleton. You can see the modification in:

https://github.com/PiranhaCMS/piranha.core/commit/4e56826beb3494712948adbbcb701617c48f994b

**Comment by willwolfram18** [comment]
@tidyui Just found that `Piranha.EF.PageRepository` also uses `App.PageTypes`. I am going to change this to use the injected `IDataService` from the constructor, seen in https://github.com/TheWolfA2/piranha.core/commit/1af05a6a4735055fa3db7132a6240b86ab702c2b
